#!/bin/sh

. $SNAP/utilities/pterodactyl-utilities

echo -n "Waiting for Pterodactyl Panel config dir... "
while [ ! -d "$PTERODACTYL_CONFIG_DIR" ]; do
	sleep 1
done

echo "done"

while true; do
	php -c $SNAP/config/php $SNAP/htdocs/cron.php
	sleep 15m
done
