#!/bin/sh

. $SNAP/utilities/php-utilities
. $SNAP/utilities/mysql-utilities
. $SNAP/utilities/pterodactyl-utilities
. $SNAP/utilities/redis-utilities

# Make sure pterodactyl panel storage directory exists
mkdir -p -m 750 $SNAP_COMMON/pterodactyl-panel/storage

# Make sure pterodactyl panel tmp directory exists
mkdir -p -m 750 $SNAP_COMMON/tmp

# We need both PHP and redis up and running
wait_for_php
wait_for_redis

# Need to install dependencies first, so we can generate a key if needed.
# TODO: We should really ship these dependencies in the snap.
echo "Installing dependencies via composer"
composer install --no-dev --prefer-dist

# If this is a new install, make sure it's configured correctly
if [ ! -d "$PTERODACTYL_CONFIG_DIR" ]; then
	echo "Configuring Pterodactyl Panel (new installation)..."
	cp -r $SNAP/htdocs/config $PTERODACTYL_CONFIG_DIR
	laravel_key=$(artisan key:generate --show)
	pterodactyl_set_key "$laravel_key"
else
	# Do nothing for now
	sleep 1
fi

# Finally, make sure pterodactyl panel is up to date.
echo "Making sure Pterodactyl Panel is fully migrated/seeded..."
artisan migrate --seed

#return_code=$?
#if [ $return_code -eq 1 ]; then
#	echo "Pterodactyl Panel is not yet installed-- no upgrade necessary"
#elif [ $return_code -eq 3 ]; then
#	echo "Pterodactyl Panel is fully upgraded"
#elif [ $return_code -ne 0 ]; then
#	echo "Unable to upgrade Pterodactyl Panel. Will try again."
#	# occ may have left it in maintenance mode, so turn that off
#	occ maintenance:mode --off
#	sleep 10 # Delaying here so systemd doesn't throttle us
#	exit 1
#fi
